services:
  - type: web
    name: proctoring-project
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k eventlet -w 1 wsgi:app
    autoDeploy: true
    healthCheckPath: /
